wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.22.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1773059552
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 4
      - 16
      - 42
      4: 3.10.18
      5: 0.22.1
      13: linux-x86_64
    e:
      0vgjtxv5g37jup97baxdh7s0bww9ojwo:
        os: Linux-5.4.0-150-generic-x86_64-with-glibc2.27
        python: CPython 3.10.18
        started_at: '2026-03-09T12:32:31.803173Z'
        program: -m cs336_basics.training_loop
        git:
          remote_url: https://github.com/JPassionQ/assignment1-basics
          commit: b6633d22abf91c390a4fc3dc696c4b720ee5a42e
        root: /home/ubuntu/cs336_assignments/assignment1-basics
        host: jingqi
        executable: /home/ubuntu/anaconda3/envs/goat/bin/python
        cpu_count: 36
        cpu_count_logical: 32
        gpu_type: NVIDIA A100 80GB PCIe
        gpu_count: 2
        disk:
          /:
            total: '266734272512'
            used: '185695862784'
        memory:
          total: '64000000000'
        gpu_nvidia:
        - name: NVIDIA A100 80GB PCIe
          memory_total: '85899345920'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-4c5b4d92-df52-daad-7eb4-03eb33912af8
        - name: NVIDIA A100 80GB PCIe
          memory_total: '85899345920'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-fb328c3d-77de-fb7d-5d9b-1c13ab8c1419
        cuda_version: '12.3'
        writer_id: 0vgjtxv5g37jup97baxdh7s0bww9ojwo
batch_size:
  desc: null
  value: 16
context_length:
  desc: null
  value: 256
epochs:
  desc: null
  value: 1000
d_model:
  desc: null
  value: 512
n_heads:
  desc: null
  value: 16
layers:
  desc: null
  value: 4
vocab_size:
  desc: null
  value: 50257
lr:
  desc: null
  value: 0.0005
weight_decay:
  desc: null
  value: 0.01
max_seq_length:
  desc: null
  value: 1024
dataset:
  desc: null
  value: tinystories_train
